sudo: required
language: node_js
node_js:
  - "8.11.1"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng test --watch false
  - ng e2e

after_success:
  if: branch = master
    - ng build --prod
    - firebase use hitched-ng
    - firebase deploy --token $FIREBASE_TOKEN